{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-length": "198",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Google Chrome\";v=\"101\"",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36",
    "sec-ch-ua-platform": "\"Windows\"",
    "content-type": "application/json",
    "accept": "*/*",
    "origin": "http://localhost:8081",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "jenkins-timestamper-offset=-19800000; JSESSIONID.69a0f5e3=node06li1bfczd14b2ubdydnh5g1g1.node0; screenResolution=1366x768"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/book-flights",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/book-flights",
  "listenerPath": "/api/*",
  "relativePath": "/api/book-flights",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/book-flights",
  "rawRequestPath": "/api/book-flights",
  "remoteAddress": "/127.0.0.1:58012",
  "requestPath": "/api/book-flights"
}